# Generated by Django 3.0.10 on 2021-06-13 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fefco',
            fields=[
                ('fefco_code', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('price_a', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_n', models.DecimalField(decimal_places=2, max_digits=8)),
                ('photo', models.ImageField(upload_to='media')),
                ('quantity', models.IntegerField()),
                ('fefco', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utils.Fefco')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utils.Layer')),
            ],
        ),
    ]
