# Generated by Django 3.0.10 on 2021-06-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_checkoutaddress_order_orderitem_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
